### ISSUE TITLE
npm install will not finish successfully

### ISSUE THREAD

**Issue by paulbwd** [bradtraversy/clientpanel_react#1] opened 2020-03-08 19:05 UTC
On trying to run npm install, this is now failing to complete successfully.

I was working on this from a video course i got from Packt Publishing (React front to back) and everything was fine until we got to the part about adding in firebase... I couldn't get it to successfully build the project at that point forwards.... so I thought Id grab the code , rebuild the project and then at least finish watching up the video course.. but sadly I still couldn't  get a successful build from a clean install of this repository.. Thanks Paul

**Comment by PaulBrownDFS** [comment] 2020-03-21 09:17
Actually this is caused by using a new version of Node.js,  now I've rolled back to version 9, this and many other npm installs now work fine..

Not sure how to close this?

**Closed** 2020-03-21 09:18 UTC
